version: "3.7"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./docker/postgres/:/var/lib/postgresql/data
    ports:
      - 5432:5432