"""empty message

Revision ID: c47bc65c50ab
Revises: ae56eb2c8653
Create Date: 2024-03-09 22:38:52.900396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47bc65c50ab'
down_revision: Union[str, None] = 'ae56eb2c8653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpn_interfaces', sa.Column('server_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'vpn_interfaces', 'vpn_servers', ['server_id'], ['id'])
    op.drop_column('vpn_interfaces', 'server')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpn_interfaces', sa.Column('server', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vpn_interfaces', type_='foreignkey')
    op.drop_column('vpn_interfaces', 'server_id')
    # ### end Alembic commands ###
